app:
    resource: @AppBundle/Controller/
    type:     annotation

admin:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
