# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    shareme_storage.amazon_s3:
        class: AmazonS3
        arguments: [["%amazon_s3.aws_key%", "%amazon_s3.aws_secret_key%"]]

    shareme_storage.photo_uploader:
        class: AppBundle\Upload\PhotoUploader
        arguments: ["@photo_storage_filesystem"]
